# Generated by Django 5.2.4 on 2025-09-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NexStormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('json_data', models.JSONField()),
            ],
            options={
                'verbose_name': 'NexStorm Data',
                'verbose_name_plural': 'NexStorm Data',
                'ordering': ['-received_at'],
            },
        ),
    ]
