# Generated by Django 5.2.7 on 2025-10-28 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('strike_type', models.IntegerField(blank=True, null=True)),
                ('nexstorm_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to='lightning.nexstormdata')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='lightning_s_timesta_27cebb_idx')],
            },
        ),
    ]
