# Generated by Django 5.2.7 on 2025-10-28 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0002_strike'),
        ('lightning', '0003_migrate_strikes_from_json'),
    ]

    operations = [
    ]
