# Generated by Django 5.2.7 on 2025-10-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0004_merge_0002_strike_0003_migrate_strikes_from_json'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='strike',
            name='lightning_s_timesta_27cebb_idx',
        ),
        migrations.RemoveField(
            model_name='strike',
            name='nexstorm_data',
        ),
        migrations.AddField(
            model_name='strike',
            name='epoch_ms',
            field=models.BigIntegerField(db_index=True, default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strike',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='strike_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
