# Generated by Django 5.2.7 on 2025-10-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0005_remove_strike_lightning_s_timesta_27cebb_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NexStormData',
        ),
        migrations.AlterField(
            model_name='strike',
            name='epoch_ms',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='strike',
            index=models.Index(fields=['timestamp'], name='lightning_s_timesta_27cebb_idx'),
        ),
        migrations.AddIndex(
            model_name='strike',
            index=models.Index(fields=['epoch_ms'], name='lightning_s_epoch_m_3682a4_idx'),
        ),
    ]
