# Generated by Django 5.2.7 on 2025-10-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0006_delete_nexstormdata_alter_strike_epoch_ms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStrikeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_date', models.DateField(db_index=True, unique=True)),
                ('cg_plus_count', models.PositiveIntegerField(default=0)),
                ('cg_minus_count', models.PositiveIntegerField(default=0)),
                ('ic_count', models.PositiveIntegerField(default=0)),
                ('other_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Strike Summary',
                'verbose_name_plural': 'Daily Strike Summaries',
                'ordering': ['-summary_date'],
            },
        ),
    ]
