# Generated by Django 5.2.4 on 2026-06-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0009_lightning_grid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightningDailyGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_date', models.DateField(db_index=True, help_text='Date in WIT')),
                ('latitude', models.FloatField(help_text='Grid cell center latitude')),
                ('longitude', models.FloatField(help_text='Grid cell center longitude')),
                ('cg_plus', models.IntegerField(default=0, help_text='CG+ strike count')),
                ('cg_minus', models.IntegerField(default=0, help_text='CG- strike count')),
                ('ic', models.IntegerField(default=0, help_text='IC (intracloud) count')),
                ('total', models.IntegerField(default=0, help_text='Total strike count')),
            ],
            options={
                'verbose_name': 'Daily Lightning Grid',
                'verbose_name_plural': 'Daily Lightning Grids',
                'ordering': ['grid_date', 'latitude', 'longitude'],
                'unique_together': {('grid_date', 'latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='LightningMonthlyGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, help_text='Year')),
                ('month', models.IntegerField(db_index=True, help_text='Month (1-12)')),
                ('latitude', models.FloatField(help_text='Grid cell center latitude')),
                ('longitude', models.FloatField(help_text='Grid cell center longitude')),
                ('cg_plus', models.IntegerField(default=0, help_text='CG+ strike count (monthly)')),
                ('cg_minus', models.IntegerField(default=0, help_text='CG- strike count (monthly)')),
                ('ic', models.IntegerField(default=0, help_text='IC count (monthly)')),
                ('total', models.IntegerField(default=0, help_text='Total strike count (monthly)')),
                ('idw_smooth', models.FloatField(blank=True, help_text='IDW-smoothed density for color gradient', null=True)),
            ],
            options={
                'verbose_name': 'Monthly Lightning Grid',
                'verbose_name_plural': 'Monthly Lightning Grids',
                'ordering': ['-year', '-month', 'latitude', 'longitude'],
                'unique_together': {('year', 'month', 'latitude', 'longitude')},
            },
        ),
        migrations.DeleteModel(
            name='LightningGrid',
        ),
    ]
