# Generated by Django 5.2.16 on 2026-08-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0010_daily_monthly_grid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lightningdailygrid',
            name='ic',
        ),
        migrations.RemoveField(
            model_name='lightningmonthlygrid',
            name='ic',
        ),
    ]
