# Generated by Django 5.2.4 on 2025-08-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gempa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, help_text='ID gabungan dari sumber API dan kode stasiun', max_length=50, null=True, unique=True)),
                ('station_code', models.CharField(db_index=True, max_length=10)),
                ('origin_datetime', models.DateTimeField(help_text='Waktu kejadian gempa dalam UTC')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('magnitudo', models.DecimalField(decimal_places=1, max_digits=3)),
                ('depth', models.IntegerField()),
                ('remark', models.CharField(max_length=191)),
                ('felt', models.BooleanField(default=False)),
                ('impact', models.CharField(blank=True, max_length=191, null=True)),
            ],
            options={
                'db_table': 'gempas',
                'ordering': ['-origin_datetime'],
            },
        ),
    ]
