# Generated by Django 5.2.4 on 2025-08-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(db_index=True, max_length=10)),
                ('channel', models.CharField(max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('percentage', models.FloatField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'station', 'channel'],
                'unique_together': {('station', 'channel', 'date')},
            },
        ),
    ]
