# Generated by Django 5.2.4 on 2025-09-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_dataavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceleroDataAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(db_index=True, help_text='Station code (e.g., JAY)', max_length=10)),
                ('channel', models.CharField(db_index=True, help_text='Channel code (e.g., EHZ)', max_length=10)),
                ('date', models.DateField(help_text='Date of the data availability record')),
                ('percentage', models.FloatField(help_text='Percentage of data available for the day (0-100)')),
            ],
            options={
                'verbose_name_plural': 'Accelero Data Availability',
                'db_table': 'accelero_data_availability',
                'ordering': ['-date', 'station', 'channel'],
                'unique_together': {('station', 'channel', 'date')},
            },
        ),
    ]
