# Generated by Django 5.2.4 on 2025-09-06 00:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_accelerodataavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='accelerodataavailability',
            name='reported_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
