# Generated by Django 5.2.4 on 2025-10-05 08:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_accelerodataavailability_reported_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarthquakeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('magnitude', models.FloatField()),
                ('depth', models.FloatField()),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('location_string', models.CharField(max_length=255)),
                ('shakemap_image', models.ImageField(upload_to='shakemaps/')),
            ],
        ),
        migrations.CreateModel(
            name='StationReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(db_index=True, max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distance_km', models.FloatField()),
                ('intensity', models.FloatField(help_text='Instrumental Intensity')),
                ('pga_ew', models.FloatField(blank=True, help_text='East-West component', null=True)),
                ('pga_ns', models.FloatField(blank=True, help_text='North-South component', null=True)),
                ('pga_ud', models.FloatField(blank=True, help_text='Up-Down (Vertical) component', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='repository.earthquakeevent')),
            ],
            options={
                'unique_together': {('event', 'station_code')},
            },
        ),
    ]
