# Generated by Django 5.2.4 on 2025-10-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_earthquakeevent_stationreading'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EarthquakeEvent',
            new_name='ShakemapEvent',
        ),
    ]
