# Generated by Django 5.2.7 on 2026-03-30 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_rename_earthquakeevent_shakemapevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONDataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('agency', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('bulan', models.CharField(blank=True, max_length=10, null=True)),
                ('json_file', models.FileField(upload_to='json_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('data_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'json_data_uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
