# Generated by Django 5.2.4 on 2026-04-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_jsondataupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeltEarthquake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_datetime', models.DateTimeField(db_index=True, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('magnitude', models.FloatField()),
                ('depth_km', models.FloatField()),
                ('wilayah', models.CharField(max_length=300)),
                ('dirasakan', models.CharField(blank=True, max_length=500)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_datetime'],
            },
        ),
    ]
