# Generated by Django 5.2.4 on 2026-04-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_felt_earthquake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shakemapevent',
            name='shakemap_image',
            field=models.ImageField(blank=True, null=True, upload_to='shakemaps/'),
        ),
    ]
