# Generated by Django 5.2.4 on 2026-04-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_shakemap_image_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='feltearthquake',
            name='img_impact_list',
            field=models.ImageField(blank=True, null=True, upload_to='felt_earthquakes/impact/'),
        ),
        migrations.AddField(
            model_name='feltearthquake',
            name='img_loc_map',
            field=models.ImageField(blank=True, null=True, upload_to='felt_earthquakes/locmap/'),
        ),
        migrations.AddField(
            model_name='feltearthquake',
            name='img_report_1',
            field=models.ImageField(blank=True, null=True, upload_to='felt_earthquakes/reports/'),
        ),
        migrations.AddField(
            model_name='feltearthquake',
            name='img_report_2',
            field=models.ImageField(blank=True, null=True, upload_to='felt_earthquakes/reports/'),
        ),
        migrations.AddField(
            model_name='feltearthquake',
            name='img_stationlist',
            field=models.ImageField(blank=True, null=True, upload_to='felt_earthquakes/stationlist/'),
        ),
    ]
