# Generated by Django 5.2.4 on 2026-04-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_felt_earthquake_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StationReading',
        ),
    ]
