# Generated by Django 5.2.4 on 2026-04-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0012_remove_stationreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='GempaMemusak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveIntegerField(help_text='Nomor urut dari katalog', unique=True)),
                ('tanggal_text', models.CharField(help_text="Tanggal sesuai tulisan asli, mis. '23 Mei 1864'", max_length=60)),
                ('tanggal', models.DateField(blank=True, db_index=True, null=True)),
                ('wilayah', models.CharField(blank=True, default='', help_text='Nama wilayah/daerah', max_length=255)),
                ('origin_time', models.TimeField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('depth_km', models.FloatField(blank=True, null=True)),
                ('magnitude', models.FloatField(blank=True, null=True)),
                ('lokasi', models.CharField(blank=True, choices=[('Darat', 'Darat'), ('Laut', 'Laut')], default='', max_length=10)),
                ('tsunami', models.BooleanField(blank=True, null=True)),
                ('wilayah_merasakan', models.TextField(blank=True, default='')),
                ('korban_kerusakan', models.TextField(blank=True, default='')),
                ('sumber', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Gempa Merusak',
                'verbose_name_plural': 'Gempa Merusak',
                'ordering': ['no'],
            },
        ),
    ]
