# Generated by Django 5.2.4 on 2026-04-23 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_add_gempa_merusak'),
    ]

    operations = [
        migrations.AddField(
            model_name='gempamemusak',
            name='provinsi',
            field=models.CharField(blank=True, choices=[('Papua', 'Papua'), ('Papua Barat', 'Papua Barat'), ('Papua Tengah', 'Papua Tengah'), ('Papua Selatan', 'Papua Selatan'), ('Papua Pegunungan', 'Papua Pegunungan'), ('Papua Barat Daya', 'Papua Barat Daya')], default='', max_length=50),
        ),
        migrations.CreateModel(
            name='GempaMemusakMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='gempa_merusak/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='repository.gempamemusak')),
            ],
            options={
                'verbose_name': 'Gempa Merusak Media',
                'verbose_name_plural': 'Gempa Merusak Media',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
