# Generated by Django 5.2.4 on 2026-04-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_gempa_merusak_provinsi_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'reference_locations',
            },
        ),
    ]
