# Generated by Django 5.2.4 on 2026-04-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0015_add_reference_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBrowser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('origin_time', models.DateTimeField(db_index=True)),
                ('magnitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('depth_km', models.FloatField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('nearest_city', models.CharField(blank=True, max_length=100)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Browser',
                'verbose_name_plural': 'Event Browser',
                'ordering': ['-origin_time'],
            },
        ),
    ]
