# Generated by Django 5.2.4 on 2026-04-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0016_eventbrowser'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbrowser',
            name='author',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
