# Generated by Django 5.2.4 on 2026-05-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0017_add_author_to_eventbrowser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gempamemusak',
            name='provinsi',
            field=models.CharField(blank=True, choices=[('Aceh', 'Aceh'), ('Sumatera Utara', 'Sumatera Utara'), ('Sumatera Barat', 'Sumatera Barat'), ('Riau', 'Riau'), ('Kepulauan Riau', 'Kepulauan Riau'), ('Jambi', 'Jambi'), ('Sumatera Selatan', 'Sumatera Selatan'), ('Bengkulu', 'Bengkulu'), ('Lampung', 'Lampung'), ('Kepulauan Bangka Belitung', 'Kepulauan Bangka Belitung'), ('DKI Jakarta', 'DKI Jakarta'), ('Jawa Barat', 'Jawa Barat'), ('Jawa Tengah', 'Jawa Tengah'), ('DI Yogyakarta', 'DI Yogyakarta'), ('Jawa Timur', 'Jawa Timur'), ('Banten', 'Banten'), ('Bali', 'Bali'), ('Nusa Tenggara Barat', 'Nusa Tenggara Barat'), ('Nusa Tenggara Timur', 'Nusa Tenggara Timur'), ('Kalimantan Barat', 'Kalimantan Barat'), ('Kalimantan Tengah', 'Kalimantan Tengah'), ('Kalimantan Selatan', 'Kalimantan Selatan'), ('Kalimantan Timur', 'Kalimantan Timur'), ('Kalimantan Utara', 'Kalimantan Utara'), ('Sulawesi Utara', 'Sulawesi Utara'), ('Gorontalo', 'Gorontalo'), ('Sulawesi Tengah', 'Sulawesi Tengah'), ('Sulawesi Barat', 'Sulawesi Barat'), ('Sulawesi Selatan', 'Sulawesi Selatan'), ('Sulawesi Tenggara', 'Sulawesi Tenggara'), ('Maluku', 'Maluku'), ('Maluku Utara', 'Maluku Utara'), ('Papua Barat Daya', 'Papua Barat Daya'), ('Papua Barat', 'Papua Barat'), ('Papua', 'Papua'), ('Papua Tengah', 'Papua Tengah'), ('Papua Pegunungan', 'Papua Pegunungan'), ('Papua Selatan', 'Papua Selatan')], default='', max_length=50),
        ),
    ]
