# Generated by Django 5.2.4 on 2026-05-15 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0018_expand_province_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationDesignSpectrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pga', models.FloatField(help_text='Peak Ground Acceleration (g)')),
                ('ss', models.FloatField(help_text='Short-period spectral accel (g)')),
                ('s1', models.FloatField(help_text='1-second spectral accel (g)')),
                ('tl', models.FloatField(help_text='Long-period transition (s)')),
                ('spectrum_b', models.JSONField(help_text='Site class B (rock)')),
                ('spectrum_c', models.JSONField(help_text='Site class C (very dense soil/soft rock)')),
                ('spectrum_d', models.JSONField(help_text='Site class D (stiff soil)')),
                ('spectrum_e', models.JSONField(help_text='Site class E (soft clay)')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design_spectrum', to='repository.station')),
            ],
            options={
                'verbose_name': 'Station Design Spectrum',
                'verbose_name_plural': 'Station Design Spectra',
            },
        ),
    ]
