# Generated by Django 5.2.4 on 2026-05-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0019_station_design_spectrum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationdesignspectrum',
            name='tl',
            field=models.FloatField(blank=True, help_text='Long-period transition (s)', null=True),
        ),
    ]
