# Generated by Django 5.2.4 on 2026-05-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0021_eventresponsespectrum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventresponsespectrum',
            options={'ordering': ['station_code', 'component'], 'verbose_name': 'Event Response Spectrum', 'verbose_name_plural': 'Event Response Spectra'},
        ),
        migrations.RemoveField(
            model_name='eventresponsespectrum',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='eventresponsespectrum',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='eventresponsespectrum',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='eventresponsespectrum',
            name='psa03',
        ),
        migrations.RemoveField(
            model_name='eventresponsespectrum',
            name='psa10',
        ),
        migrations.RemoveField(
            model_name='eventresponsespectrum',
            name='psa30',
        ),
        migrations.AddField(
            model_name='eventresponsespectrum',
            name='spectrum',
            field=models.JSONField(default=[], help_text='List of {"T": period_s, "Sa": value_g}'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventresponsespectrum',
            name='component',
            field=models.CharField(help_text='e.g. HNE, HNN, HNZ', max_length=10),
        ),
    ]
