# Generated by Django 5.2.4 on 2026-05-16 10:48

import repository.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0022_alter_eventresponsespectrum_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStationWaveform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=100)),
                ('station_code', models.CharField(max_length=10)),
                ('component', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to=repository.models._waveform_image_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event Station Waveform',
                'verbose_name_plural': 'Event Station Waveforms',
                'ordering': ['station_code', 'component'],
                'unique_together': {('event_id', 'station_code', 'component')},
            },
        ),
    ]
