# Generated by Django 5.2.4 on 2026-05-28 00:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0023_eventstationwaveform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bulan', models.CharField(help_text='Bulan (1-12)', max_length=2)),
                ('tahun', models.CharField(max_length=4)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='bulletins/covers/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='bulletins/pdfs/', verbose_name='File PDF')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Buletin',
                'verbose_name_plural': 'Buletin',
                'db_table': 'bulletins',
                'ordering': ['-tahun', '-bulan'],
            },
        ),
    ]
