# Generated by Django 5.2.4 on 2026-05-28 01:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0024_bulletin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiaranPress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, default='', max_length=191)),
                ('content', models.TextField(blank=True, help_text='HTML content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='siaranpress/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Siaran Press',
                'verbose_name_plural': 'Siaran Press',
                'db_table': 'siaran_press',
                'ordering': ['-created_at'],
            },
        ),
    ]
