# Generated by Django 5.2.4 on 2026-06-10 03:22

import repository.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0024_bulletin'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstationwaveform',
            name='mseed',
            field=models.FileField(blank=True, null=True, upload_to=repository.models._waveform_mseed_path),
        ),
    ]
