# Generated by Django 5.2.16 on 2026-08-01 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0025_siaranpress'),
        ('repository', '0026_add_mseed_to_waveform'),
    ]

    operations = [
    ]
