# Generated by Django 5.2.16 on 2026-09-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0027_merge_0025_siaranpress_0026_add_mseed_to_waveform'),
    ]

    operations = [
        migrations.AddField(
            model_name='gempamemusak',
            name='dip',
            field=models.FloatField(blank=True, help_text='Dip (deg) nodal plane 1', null=True),
        ),
        migrations.AddField(
            model_name='gempamemusak',
            name='rake',
            field=models.FloatField(blank=True, help_text='Rake (deg) nodal plane 1', null=True),
        ),
        migrations.AddField(
            model_name='gempamemusak',
            name='strike',
            field=models.FloatField(blank=True, help_text='Strike (deg) nodal plane 1', null=True),
        ),
        migrations.AddField(
            model_name='gempamemusak',
            name='tensor_source',
            field=models.CharField(blank=True, default='', help_text='Source of the focal mechanism, e.g. USGS', max_length=60),
        ),
    ]
