# Generated by Django 5.2.4 on 2026-04-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surat_tugas', models.CharField(max_length=255)),
                ('peralatan', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('BELUM_DIKEMBALIKAN', 'Belum Dikembalikan'), ('SUDAH_DIKEMBALIKAN', 'Sudah Dikembalikan'), ('RUSAK', 'Rusak'), ('HILANG', 'Hilang')], default='BELUM_DIKEMBALIKAN', max_length=25)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Peralatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_alat', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('BMN', 'BMN'), ('SUKU_CADANG', 'Suku Cadang')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nama_alat'],
            },
        ),
    ]
