# Generated by Django 5.2.4 on 2026-04-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_pm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peralatan',
            name='status',
            field=models.CharField(choices=[('BMN', 'BMN'), ('SUKU_CADANG', 'Suku Cadang')], default='SUKU_CADANG', max_length=20),
        ),
    ]
