# Generated by Django 5.2.4 on 2026-07-16 18:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_pm', '0004_peminjaman_tanggal_peminjaman'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeralatanSukuCadang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_alat', models.CharField(max_length=150, verbose_name='Jenis Alat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Peralatan Suku Cadang',
                'verbose_name_plural': 'Peralatan Suku Cadang',
                'ordering': ['jenis_alat'],
            },
        ),
        migrations.CreateModel(
            name='ManajemenSukuCadang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_masuk', models.DateField(default=datetime.date.today, verbose_name='Tanggal Masuk')),
                ('merk', models.CharField(max_length=150, verbose_name='Merk')),
                ('serial_number', models.CharField(max_length=150, verbose_name='Serial Number')),
                ('jumlah', models.PositiveIntegerField(default=1, verbose_name='Jumlah')),
                ('status', models.CharField(choices=[('BELUM_TERPASANG', 'Belum Terpasang'), ('SUDAH_TERPASANG', 'Sudah Terpasang'), ('RUSAK', 'Rusak')], default='BELUM_TERPASANG', max_length=20, verbose_name='Status')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manajemen_items', to='monitoring_pm.peralatansukucadang', verbose_name='Jenis')),
            ],
            options={
                'verbose_name': 'Manajemen Suku Cadang',
                'verbose_name_plural': 'Manajemen Suku Cadang',
                'ordering': ['-tanggal_masuk', '-created_at'],
            },
        ),
    ]
