# Generated by Django 5.2.16 on 2026-08-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_pm', '0005_peralatansukucadang_manajemensukucadang'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='tanggal_pengembalian',
            field=models.DateField(blank=True, null=True),
        ),
    ]
