# Generated by Django 5.2.4 on 2025-08-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagneticObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField()),
                ('observer', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=50)),
                ('cr_awal', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cl_awal', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cr_akhir', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cl_akhir', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('deklinasi_readings', models.JSONField(blank=True, null=True)),
                ('inklinasi_readings', models.JSONField(blank=True, null=True)),
                ('meridian_1', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('meridian_2', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('declination', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('inclination', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('horizontal_intensity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_intensity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-observation_date', '-session'],
            },
        ),
    ]
