# Generated by Django 5.2.7 on 2025-10-08 03:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earthquake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='ID unik dari sumber API untuk menghindari duplikasi', max_length=100, unique=True)),
                ('event_time', models.DateTimeField(db_index=True, verbose_name='Waktu Kejadian')),
                ('location_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Titik Episentrum')),
                ('depth', models.FloatField(verbose_name='Kedalaman (km)')),
                ('magnitude', models.FloatField(db_index=True, verbose_name='Magnitudo')),
                ('region', models.CharField(max_length=255, verbose_name='Wilayah')),
            ],
            options={
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='Precursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_timestamp', models.DateTimeField(help_text='Waktu anomali terdeteksi', verbose_name='Waktu Anomali')),
                ('predicted_start_date', models.DateField(verbose_name='Tanggal Mulai Prediksi')),
                ('predicted_end_date', models.DateField(verbose_name='Tanggal Akhir Prediksi')),
                ('predicted_magnitude', models.FloatField(verbose_name='Prediksi Magnitudo')),
                ('magnitude_tolerance', models.FloatField(default=0.5, help_text='Contoh: Jika prediksi 6.0 dan toleransi 0.5, maka rentang valid adalah 5.5 - 6.5', verbose_name='Toleransi Magnitudo (+/-)')),
                ('location_description', models.CharField(help_text='Deskripsi singkat mengenai area prediksi', max_length=255, verbose_name='Deskripsi Lokasi')),
                ('location_polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Area prediksi yang digambar di peta', null=True, srid=4326, verbose_name='Area Poligon Prediksi')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Terbukti?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validating_earthquake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_precursors', to='magnet.earthquake', verbose_name='Gempa yang Memvalidasi')),
            ],
        ),
    ]
