# Generated by Django 5.2.7 on 2025-10-08 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnet', '0002_earthquake_precursor'),
        ('repository', '0007_rename_earthquakeevent_shakemapevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precursor',
            name='validating_earthquake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_precursors', to='repository.gempa', verbose_name='Gempa yang Memvalidasi'),
        ),
        migrations.DeleteModel(
            name='Earthquake',
        ),
    ]
