# Generated by Django 5.2.7 on 2025-10-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnet', '0003_alter_precursor_validating_earthquake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precursor',
            name='azimuth',
            field=models.FloatField(blank=True, null=True, verbose_name='Azimuth (°)'),
        ),
    ]
