# Generated by Django 5.2.7 on 2026-03-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnet', '0005_magnetdataavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='magneticobservation',
            name='east_component',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='magneticobservation',
            name='north_component',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='magneticobservation',
            name='vertical_intensity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
