# Generated by Django 5.2.4 on 2026-04-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnet', '0006_magneticobservation_east_component_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LEMIStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('not_responding', 'Not Responding'), ('not_running', 'Not Running')], max_length=20)),
                ('computer_name', models.CharField(blank=True, max_length=100)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reported_at'],
                'get_latest_by': 'reported_at',
            },
        ),
    ]
