# Generated by Django 5.2.4 on 2026-04-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnet', '0007_lemistatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(choices=[('lemi', 'LEMI-018'), ('proton', 'Proton'), ('nexstorm', 'Nexstorm')], max_length=20)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('not_responding', 'Not Responding'), ('not_running', 'Not Running')], max_length=20)),
                ('computer_name', models.CharField(blank=True, max_length=100)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
