# Generated by Django 5.2.16 on 2026-10-02 18:12

import magnet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnet', '0008_instrumentstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='FmiIndicesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('K', 'K Indices'), ('A', 'A Indices')], max_length=1, verbose_name='Jenis Indeks')),
                ('tanggal', models.DateField(verbose_name='Tanggal (WIT)')),
                ('image', models.ImageField(upload_to=magnet.models.fmi_indices_upload_to, verbose_name='Gambar')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='URL Sumber')),
                ('etag', models.CharField(blank=True, max_length=100, verbose_name='ETag Sumber')),
                ('sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA-256')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='Ukuran (byte)')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Pengambilan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Waktu Pembaruan')),
                ('telegram_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Terkirim ke Telegram')),
            ],
            options={
                'verbose_name': 'Indeks K & A Magnetbumi',
                'verbose_name_plural': 'Indeks K & A Magnetbumi',
                'ordering': ['-tanggal', 'jenis'],
                'unique_together': {('jenis', 'tanggal')},
            },
        ),
    ]
