# Generated by Django 6.0.4 on 2026-04-30 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('origin_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('depth_km', models.FloatField()),
                ('magnitude', models.FloatField(blank=True, null=True)),
                ('magnitude_type', models.CharField(blank=True, max_length=8, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_committed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-origin_time'],
            },
        ),
        migrations.CreateModel(
            name='QCRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.PositiveIntegerField(help_text='1, 2, 3, … for successive commits on this event')),
                ('committed_at', models.DateTimeField(auto_now_add=True)),
                ('overview_image', models.ImageField(blank=True, help_text='Multi-station record-section plot for this run', null=True, upload_to='overview_images/')),
                ('notes', models.TextField(blank=True, default='', help_text="Optional note from the worker (e.g. 'after re-pick of ABCD')")),
                ('snap_origin_time', models.DateTimeField(blank=True, null=True)),
                ('snap_latitude', models.FloatField(blank=True, null=True)),
                ('snap_longitude', models.FloatField(blank=True, null=True)),
                ('snap_depth_km', models.FloatField(blank=True, null=True)),
                ('snap_magnitude', models.FloatField(blank=True, null=True)),
                ('snap_magnitude_type', models.CharField(blank=True, max_length=8, null=True)),
                ('snap_region', models.CharField(blank=True, max_length=255, null=True)),
                ('evaluation_mode', models.CharField(blank=True, max_length=16, null=True)),
                ('evaluation_status', models.CharField(blank=True, max_length=16, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='qc_review.event')),
            ],
            options={
                'ordering': ['-run_number'],
                'unique_together': {('event', 'run_number')},
            },
        ),
        migrations.CreateModel(
            name='StationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=4)),
                ('station', models.CharField(max_length=8)),
                ('station_lat', models.FloatField(blank=True, null=True)),
                ('station_lon', models.FloatField(blank=True, null=True)),
                ('distance_deg', models.FloatField(blank=True, null=True)),
                ('azimuth', models.FloatField(blank=True, null=True)),
                ('distance_class', models.CharField(choices=[('local', 'Local'), ('regional', 'Regional'), ('teleseismic', 'Teleseismic')], default='regional', max_length=16)),
                ('filter_freqmin', models.FloatField()),
                ('filter_freqmax', models.FloatField()),
                ('analyst_p', models.DateTimeField(blank=True, null=True)),
                ('analyst_s', models.DateTimeField(blank=True, null=True)),
                ('auto_p', models.DateTimeField(blank=True, null=True)),
                ('auto_s', models.DateTimeField(blank=True, null=True)),
                ('auto_p_prob', models.FloatField(blank=True, null=True)),
                ('auto_s_prob', models.FloatField(blank=True, null=True)),
                ('delta_p', models.FloatField(blank=True, help_text='auto_P − analyst_P, seconds', null=True)),
                ('delta_s', models.FloatField(blank=True, help_text='auto_S − analyst_S, seconds', null=True)),
                ('qc_flag', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red'), ('unknown', 'Unknown')], default='unknown', max_length=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='waveform_images/')),
                ('waveform_file', models.FileField(blank=True, null=True, upload_to='waveforms/')),
                ('reviewer_note', models.TextField(blank=True, default='')),
                ('reviewer_action', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted analyst pick'), ('revised', 'Pick revision needed'), ('rejected', 'Reject station')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_name', models.CharField(blank=True, default='', max_length=64)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_results', to='qc_review.qcrun')),
            ],
            options={
                'ordering': ['distance_deg', 'station'],
                'unique_together': {('run', 'network', 'station')},
            },
        ),
    ]
