# Generated by Django 5.2.7 on 2026-01-22 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jadwal', '0006_jadwalhvsampler'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisPerjadin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tarif_harian', models.DecimalField(decimal_places=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='PerjalananDinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tujuan', models.CharField(max_length=255)),
                ('tgl_mulai', models.DateField()),
                ('tgl_selesai', models.DateField()),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perjadin.jenisperjadin')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perjadins', to='jadwal.pegawai')),
            ],
        ),
    ]
