# Generated by Django 5.2.7 on 2026-01-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perjadin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perjalanandinas',
            name='kegiatan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
