# Generated by Django 5.2.4 on 2025-09-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hujan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('hilman', models.FloatField(default=0)),
                ('obs', models.FloatField()),
                ('kategori', models.CharField(max_length=50)),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('petugas', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'hujan',
                'db_table': 'hujan',
                'ordering': ['-tanggal'],
            },
        ),
    ]
