# Generated by Django 5.2.4 on 2025-09-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hujan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hujan',
            name='petugas',
            field=models.CharField(default='staff ops', max_length=50),
        ),
    ]
