# Generated by Django 5.2.4 on 2026-05-03 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.FloatField(default=0)),
                ('channel', models.CharField(default='HNN', max_length=10)),
                ('sensor', models.CharField(blank=True, max_length=50)),
                ('digitizer', models.CharField(blank=True, max_length=50)),
                ('kota', models.CharField(blank=True, max_length=50)),
                ('provinsi', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('network', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('on', 'ON'), ('gap', 'GAP'), ('off', 'OFF')], default='off', max_length=10)),
                ('latency', models.FloatField(blank=True, null=True)),
                ('last_packet_time', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('channel_info', models.CharField(blank=True, max_length=50)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='stations.station')),
            ],
        ),
    ]
