# Generated by Django 5.2.4 on 2026-05-03 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationAvailabilitySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampled_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(max_length=10)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='stations.station')),
            ],
            options={
                'indexes': [models.Index(fields=['station', 'sampled_at'], name='stations_st_station_e6bbce_idx')],
            },
        ),
    ]
