# Generated by Django 5.2.4 on 2026-05-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_stationavailabilitysample'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='station_type',
            field=models.CharField(choices=[('seismic', 'Seismograph'), ('accelero', 'Accelerometer')], db_index=True, default='accelero', max_length=10),
        ),
    ]
