# Generated by Django 5.2.16 on 2026-08-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('nama_pelapor', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nama_terlapor', models.CharField(max_length=255)),
                ('jabatan', models.CharField(max_length=255)),
                ('materi_pengaduan', models.CharField(max_length=255)),
                ('isi_pengaduan', models.TextField()),
                ('status', models.CharField(choices=[('baru', 'Baru'), ('diproses', 'Diproses'), ('selesai', 'Selesai')], default='baru', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaduan',
                'verbose_name_plural': 'Pengaduan',
                'db_table': 'pengaduan',
                'ordering': ['-created_at'],
            },
        ),
    ]
