# Generated by Django 5.2.7 on 2025-12-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarthquakeEvent',
            fields=[
                ('event_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('origin_time', models.DateTimeField()),
                ('magnitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('depth', models.FloatField(help_text='Depth in km')),
                ('phases', models.IntegerField(blank=True, help_text='Number of phases', null=True)),
                ('agency', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('event_type', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(max_length=255)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Earthquake Event',
                'verbose_name_plural': 'Earthquake Events',
                'ordering': ['-origin_time'],
            },
        ),
    ]
