# Generated by Django 5.2.7 on 2025-12-07 01:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earthquakeevent',
            options={'ordering': ['-origin_time'], 'verbose_name': 'Earthquake Event'},
        ),
        migrations.AddField(
            model_name='earthquakeevent',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='earthquakeevent',
            name='phases',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
