"""
Django settings for datin_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from celery.schedules import crontab
from decouple import config, Csv       # ✅ config comes from decouple
from dotenv import load_dotenv        # ✅ load_dotenv comes from dotenv




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Auto-detect environment and load correct .env file
ENVIRONMENT = os.getenv('ENVIRONMENT', 'development').lower()

if ENVIRONMENT == 'production':
    env_file = BASE_DIR / '.env.production'
else:
    env_file = BASE_DIR / '.env.local'
    if not env_file.exists():
        env_file = BASE_DIR / '.env'

if env_file.exists():
    load_dotenv(env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'rest_framework',
    'rest_framework.authtoken',
    'tailwind',
    'theme',
    'django_browser_reload',

    'repository',
    'magnet',
    'hujan.apps.HujanConfig',
    'almanac',
    'lightning',
    'wrsng',
    'monitor',
    'logbook',
    'jadwal',
    'maintenance',
    'perjadin',
    'arsip',
    'qc_review',
    'stations',
    'layanan.apps.LayananConfig',
    'guests.apps.GuestsConfig',
    'pengaduan.apps.PengaduanConfig',
]

SEEDLINK_HOST = '202.90.199.206'   # Accelerometer SeedLink
SEEDLINK_PORT = 18123

SEISMIC_SEEDLINK_HOST = config('SEISMIC_SEEDLINK_HOST', default='202.90.198.101')  # Seismic SeedLink
SEISMIC_SEEDLINK_PORT = config('SEISMIC_SEEDLINK_PORT', default=18000, cast=int)

# Add this to the bottom of the file
INTERNAL_IPS = [
    "127.0.0.1","36.91.166.189"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    'theme.middleware.ActivityLogMiddleware',
]

ROOT_URLCONF = 'datin_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'theme.context_processors.seo',
            ],
        },
    },
]

WSGI_APPLICATION = 'datin_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.contrib.gis.db.backends.postgis'),
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
        'CONN_MAX_AGE': 60,  # keep DB connections alive for 60s
        'OPTIONS': {
            'connect_timeout': 5,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# settings.py

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# 'theme' is an installed app, so AppDirectoriesFinder already collects
# theme/static. Listing it here as well made every file resolve twice (the
# "Found another file with the destination path ..." collectstatic warning).
STATICFILES_DIRS = []

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TAILWIND_APP_NAME = 'theme'

LOGIN_REDIRECT_URL = '/dashboard/'

LOGOUT_REDIRECT_URL = 'login'

DEBUG = config('DEBUG', default=False, cast=bool)

if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': config('REDIS_CACHE_URL', default='redis://localhost:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}


HUJAN_API_URL = 'http://36.91.166.188/api/hujans/today'
CELERY_BEAT_SCHEDULE = {
    # PRIMARY IMPORT: Run at 00:15 UTC = 09:15 WIT
    # This gives users 45 minutes after 08:30 WIT input time to ensure data is ready
    'import-hujan-data-daily': {
        'task': 'hujan.tasks.import_today_hujan_data',
        'schedule': crontab(minute=15, hour=0),  # 00:15 UTC = 09:15 WIT
    },
    
    # RETRY IMPORT: Run at 02:15 UTC = 11:15 WIT
    # Catches any delayed data updates or API availability issues
    'import-hujan-data-retry': {
        'task': 'hujan.tasks.import_hujan_data_retry',
        'schedule': crontab(minute=15, hour=2),  # 02:15 UTC = 11:15 WIT
    },
    
    'process-shakemaps-daily': {
        'task': 'repository.tasks.run_process_shakemaps',
        'schedule': crontab(minute=15, hour=23),  # Runs every day at 23:15 PM
    },

    'fetch-bmkg-felt-hourly': {
        'task': 'repository.tasks.fetch_bmkg_felt_task',
        'schedule': crontab(minute=0),  # Hourly: at minute 0 of every hour, UTC
    },
    
    'process-yesterday-nexstorm-db3': {
        'task': 'lightning.tasks.process_yesterday_nexstorm_file',
        'schedule': crontab(minute=5, hour=0),   # Berjalan setiap hari pukul 00:05
    },
    
    'export-gmt-history-daily': {
        'task': 'monitor.tasks.export_and_sync_gmt_history',
        'schedule': crontab(minute=53, hour=21),  # Runs every day at 21:37
    },

    'check-gempa-merusak-daily': {
        'task': 'repository.tasks.check_gempa_merusak_task',
        'schedule': crontab(minute=30, hour=1),  # 01:30 UTC = 08:30 WIB / 10:30 WIT
    },

    'send-birthday-wishes-daily': {
        'task': 'jadwal.tasks.send_birthday_wishes_task',
        'schedule': crontab(minute=0, hour=22),  # 22:00 UTC = 07:00 WIT next day
    },

    'compute-yesterday-daily-grid': {
        'task': 'lightning.tasks.compute_yesterday_daily_grid',
        'schedule': crontab(minute=10, hour=0),  # 00:10 UTC = 09:10 WIT
    },

    'compute-previous-monthly-grid': {
        'task': 'lightning.tasks.compute_previous_monthly_grid',
        'schedule': crontab(minute=15, hour=0, day_of_month=1),
    },
}

# settings.py
SUNMOON_CITIES = [
    {"name": "Jayapura",      "lat": -2.533, "lon": 140.717},
    {"name": "Biak",          "lat": -1.178, "lon": 136.084},
    {"name": "Sarmi",         "lat": -1.867, "lon": 138.750},
    {"name": "Sentani",       "lat": -2.575, "lon": 140.516},
    {"name": "Wamena",        "lat": -4.083, "lon": 138.950},
    {"name": "Merauke",       "lat": -8.493, "lon": 140.404},
    {"name": "Asmat",         "lat": -5.000, "lon": 138.500},   # region center
    {"name": "Boven Digoel",  "lat": -5.742, "lon": 140.343},
    {"name": "Nabire",        "lat": -3.364, "lon": 135.496},
    {"name": "Keerom",        "lat": -3.350, "lon": 140.783},   # Waris area approx.
    {"name": "Waropen",       "lat": -2.233, "lon": 136.533},
    {"name": "Kep. Yapen",    "lat": -1.752, "lon": 136.202},   # Serui town
    {"name": "Mimika",        "lat": -4.528, "lon": 136.888},   # Timika
    {"name": "Kaimana",       "lat": -3.655, "lon": 133.774},
    {"name": "Wondama",       "lat": -2.720, "lon": 134.507},   # Rasiei/Wasior area
    {"name": "Ransiki",       "lat": -1.483, "lon": 134.167},
    {"name": "Manokwari",     "lat": -0.862, "lon": 134.062},
    {"name": "Sorong",        "lat": -0.867, "lon": 131.250},
    {"name": "Fakfak",        "lat": -2.923, "lon": 132.296},
    {"name": "Raja Ampat",    "lat": -0.233, "lon": 130.517},   # Waisai
]

# --- ADD THE MEDIA FILE CONFIGURATION BELOW ---

MEDIA_URL = '/media/'

# The absolute path to the folder where media files will be stored
MEDIA_ROOT = BASE_DIR / 'media'

# Absolute path to the directory where NexStorm .db3 files are placed.
# Override in .env / .env.production so it stays correct regardless of BASE_DIR.
LIGHTNING_DB3_DIR = config('LIGHTNING_DB3_DIR', default=str(BASE_DIR / 'lightning' / 'db3'))

# Matikan header COOP agar warning di console hilang
SECURE_CROSS_ORIGIN_OPENER_POLICY = None


# --- Telegram Configuration ---
TELEGRAM_BOT_TOKEN = config('TELEGRAM_BOT_TOKEN', default='')
TELEGRAM_CHAT_ID = config('TELEGRAM_CHAT_ID', default='')

# If using Gmail, you need an "App Password"
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# --- SCP / Remote Server Configuration ---
BACKUP_REMOTE_HOST = config('BACKUP_REMOTE_HOST', default='')
BACKUP_REMOTE_USER = config('BACKUP_REMOTE_USER', default='')
BACKUP_REMOTE_PATH = config('BACKUP_REMOTE_PATH', default='/var/backups/datin/') # Path on remote server

# settings.py
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880   # 5MB

FDSNWS_URL = config('FDSNWS_URL', default='http://172.21.63.51:8080')

QUAKELINK_PUSH_TOKEN    = config('QUAKELINK_PUSH_TOKEN',    default='')
LEMI_MONITOR_TOKEN      = config('LEMI_MONITOR_TOKEN',      default='')
SEISMIC_STATUS_TOKEN    = config('SEISMIC_STATUS_TOKEN',    default='')
PSA5_API_TOKEN          = config('PSA5_API_TOKEN',          default='')

# SEO / Analytics
GA_MEASUREMENT_ID = config('GA_MEASUREMENT_ID', default='')
SITE_URL          = config('SITE_URL', default='http://36.91.166.189')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}
