"""
Django settings for datin_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5)ywvh!%rto_a6qs4ry9di5(g-qvs3!io6@8dcwn7^2$x^-z_q'

ALLOWED_HOSTS = [
    "36.91.166.189",
    "127.0.0.1",
    "localhost",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'tailwind',
    'theme',
    'django_browser_reload',

    'repository',
    'magnet',
    'hujan.apps.HujanConfig',
    'almanac',
    'lightning',
    'wrsng',
    'monitor',
    'logbook',
    'jadwal',
    'maintenance',
]

# Add this to the bottom of the file
INTERNAL_IPS = [
    "127.0.0.1","36.91.166.189"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware", 
]

ROOT_URLCONF = 'datin_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'datin_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'datin',
        'USER': 'jambari',
        'PASSWORD': 'Jay97696',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# settings.py

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATICFILES_DIRS = [BASE_DIR / 'theme/static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TAILWIND_APP_NAME = 'theme'

LOGIN_REDIRECT_URL = 'dashboard'

LOGOUT_REDIRECT_URL = 'login'

DEBUG = False
# DEBUG = True

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'



CELERY_BEAT_SCHEDULE = {
    'import-earthquake-data-every-minute': {
        'task': 'repository.tasks.sync_earthquake_data_task',
        'schedule': crontab(minute='*'),
    },
    'import-hujan-data-daily': {
        'task': 'hujan.tasks.import_today_hujan_data',
        'schedule': crontab(minute=1, hour=2),
    },
    'process-shakemaps-daily': {
        'task': 'repository.tasks.run_process_shakemaps',
        'schedule': crontab(minute=15, hour=23), # Runs every day at 11:15 PM
    },

    # --- TAMBAHKAN JADWAL BARU INI ---
    'process-yesterday-nexstorm-db3': {
        'task': 'lightning.tasks.process_yesterday_nexstorm_file', # Nama task dari @shared_task
        'schedule': crontab(minute=5, hour=0), # Berjalan setiap hari pukul 00:05
    },
    # --- AKHIR JADWAL BARU ---
}

# settings.py
SUNMOON_CITIES = [
    {"name": "Jayapura",      "lat": -2.533, "lon": 140.717},
    {"name": "Biak",          "lat": -1.178, "lon": 136.084},
    {"name": "Sarmi",         "lat": -1.867, "lon": 138.750},
    {"name": "Sentani",       "lat": -2.575, "lon": 140.516},
    {"name": "Wamena",        "lat": -4.083, "lon": 138.950},
    {"name": "Merauke",       "lat": -8.493, "lon": 140.404},
    {"name": "Asmat",         "lat": -5.000, "lon": 138.500},   # region center
    {"name": "Boven Digoel",  "lat": -5.742, "lon": 140.343},
    {"name": "Nabire",        "lat": -3.364, "lon": 135.496},
    {"name": "Keerom",        "lat": -3.350, "lon": 140.783},   # Waris area approx.
    {"name": "Waropen",       "lat": -2.233, "lon": 136.533},
    {"name": "Kep. Yapen",    "lat": -1.752, "lon": 136.202},   # Serui town
    {"name": "Mimika",        "lat": -4.528, "lon": 136.888},   # Timika
    {"name": "Kaimana",       "lat": -3.655, "lon": 133.774},
    {"name": "Wondama",       "lat": -2.720, "lon": 134.507},   # Rasiei/Wasior area
    {"name": "Ransiki",       "lat": -1.483, "lon": 134.167},
    {"name": "Manokwari",     "lat": -0.862, "lon": 134.062},
    {"name": "Sorong",        "lat": -0.867, "lon": 131.250},
    {"name": "Fakfak",        "lat": -2.923, "lon": 132.296},
    {"name": "Raja Ampat",    "lat": -0.233, "lon": 130.517},   # Waisai
]

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# --- ADD THE MEDIA FILE CONFIGURATION BELOW ---

MEDIA_URL = '/media/'

# The absolute path to the folder where media files will be stored
MEDIA_ROOT = BASE_DIR / 'media'

# Matikan header COOP agar warning di console hilang
SECURE_CROSS_ORIGIN_OPENER_POLICY = None


# --- Telegram Configuration ---
# Get this from @BotFather
TELEGRAM_BOT_TOKEN = '8558923741:AAGND-p6Xfvk-F62xNj_pYXS3G7NYhIoVh4' 

# Get this by adding the bot to the group and checking API updates, 
# or use a bot like @getidsbot to find the group ID (starts with -100...)
TELEGRAM_CHAT_ID = '-1003332108158'

# If using Gmail, you need an "App Password"
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'mikrotremor91@gmail.com'
EMAIL_HOST_PASSWORD = 'Palau2025!@' 

# --- SCP / Remote Server Configuration ---
BACKUP_REMOTE_HOST = '36.91.166.188'     # IP of the other server
BACKUP_REMOTE_USER = 'jamz'             # User on remote server
BACKUP_REMOTE_PATH = '/var/backups/datin/' # Path on remote server

# settings.py
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880   # 5MB
