# Generated by Django 5.2.16 on 2026-08-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('dari', models.CharField(max_length=255)),
                ('keperluan', models.CharField(max_length=255)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('foto', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'guests',
                'ordering': ['-created_at'],
            },
        ),
    ]
