# Generated by Django 5.2.7 on 2025-12-16 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_alat', models.CharField(max_length=100)),
                ('jenis', models.CharField(choices=[('SEIS', 'Seismometer'), ('ACC', 'Accelerograph'), ('MAG', 'Magnetometer'), ('PETIR', 'Lightning Detector'), ('AQ', 'Air Quality'), ('WRS', 'WRS New Gen'), ('RAIN', 'Rain Gauge')], max_length=10)),
                ('merk_tipe', models.CharField(blank=True, max_length=100, null=True, verbose_name='Merk / Tipe')),
                ('lokasi', models.CharField(help_text='Nama Lokasi atau Desa', max_length=100)),
                ('shelter', models.CharField(help_text='Kode Shelter/Station', max_length=100)),
                ('status', models.CharField(choices=[('AKTIF', 'Aktif'), ('BERMASALAH', 'Bermasalah'), ('MATI', 'Mati/Rusak Total'), ('MAINTENANCE', 'Sedang Maintenance')], default='AKTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['shelter', 'jenis'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul Masalah')),
                ('kategori', models.CharField(choices=[('POWER', 'Power/Listrik'), ('SENSOR', 'Sensor Error'), ('KOM', 'Komunikasi/Sinyal'), ('LING', 'Lingkungan (Suhu/Vandal/Banjir)'), ('LAIN', 'Lain-lain')], max_length=10)),
                ('deskripsi', models.TextField()),
                ('prioritas', models.CharField(choices=[('TINGGI', 'Tinggi (Segera)'), ('SEDANG', 'Sedang'), ('RENDAH', 'Rendah')], default='SEDANG', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open (Baru)'), ('PROG', 'In Progress'), ('DONE', 'Selesai')], default='OPEN', max_length=10)),
                ('tanggal_lapor', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='maintenance.instrument')),
                ('pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL, verbose_name='PIC / Teknisi')),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('tindakan', models.TextField(help_text='Detail tindakan perbaikan yang dilakukan')),
                ('oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='maintenance.issue')),
            ],
        ),
    ]
