# Generated by Django 5.2.7 on 2025-12-12 08:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('waktu_dibuat', models.DateTimeField(auto_now_add=True)),
                ('shift', models.CharField(choices=[('Pagi', 'Pagi'), ('Siang', 'Siang'), ('Malam', 'Malam'), ('Pagi Siang', 'Pagi Siang'), ('Pagi Siang Malam', 'Pagi Siang Malam')], max_length=50)),
                ('seiscomp_seismik', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=3, verbose_name='Seiscomp Seismik')),
                ('seiscomp_accelero', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=3, verbose_name='Seiscomp Accelero')),
                ('esdx', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=3, verbose_name='ESDX')),
                ('petir', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=3, verbose_name='Petir')),
                ('lemi', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=3, verbose_name='LEMI')),
                ('proton', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=3, verbose_name='Proton')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('petugas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logbook Harian',
                'verbose_name_plural': 'Logbook Harian',
                'ordering': ['-tanggal', '-waktu_dibuat'],
            },
        ),
    ]
