# Generated by Django 5.2.7 on 2025-12-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='esdx',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=3, verbose_name='ESDX'),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='lemi',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=3, verbose_name='LEMI'),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='petir',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=3, verbose_name='Petir'),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='proton',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=3, verbose_name='Proton'),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='seiscomp_accelero',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=3, verbose_name='Seiscomp Accelero'),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='seiscomp_seismik',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=3, verbose_name='Seiscomp Seismik'),
        ),
    ]
