# Generated by Django 5.2.7 on 2025-12-12 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_alter_logbook_esdx_alter_logbook_lemi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='petugas_sebelum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_as_previous', to=settings.AUTH_USER_MODEL, verbose_name='Petugas Shift Sebelumnya'),
        ),
        migrations.AddField(
            model_name='logbook',
            name='petugas_selanjutnya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_as_next', to=settings.AUTH_USER_MODEL, verbose_name='Petugas Shift Selanjutnya'),
        ),
        migrations.AddField(
            model_name='logbook',
            name='status_absen',
            field=models.CharField(choices=[('Masuk', 'Awal Shift (Masuk)'), ('Pulang', 'Akhir Shift (Pulang)')], default='Masuk', max_length=20, verbose_name='Status Absen'),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='petugas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_as_petugas', to=settings.AUTH_USER_MODEL),
        ),
    ]
