# Generated by Django 5.2.7 on 2025-12-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_logbook_petugas_sebelum_logbook_petugas_selanjutnya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='hv_berat_kertas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Berat Kertas (gr)'),
        ),
        migrations.AddField(
            model_name='logbook',
            name='hv_counter_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Counter Hour'),
        ),
        migrations.AddField(
            model_name='logbook',
            name='hv_flow_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Flow Rate'),
        ),
    ]
