# Generated by Django 5.2.7 on 2026-01-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_logbook_hv_berat_kertas_logbook_hv_counter_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='shift',
            field=models.CharField(choices=[('Pagi', 'Pagi'), ('Siang', 'Siang'), ('Malam', 'Malam'), ('Pagi Siang', 'Pagi Siang'), ('Malam Tengah Malam', 'Malam Tengah Malam'), ('Pagi Siang Malam', 'Pagi Siang Malam')], max_length=50),
        ),
    ]
