# Generated by Django 5.2.7 on 2026-01-01 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_alter_logbook_shift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logbook',
            name='petugas_sebelum',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='petugas_selanjutnya',
        ),
        migrations.AddField(
            model_name='logbook',
            name='petugas_sebelum',
            field=models.ManyToManyField(blank=True, related_name='logs_as_previous', to=settings.AUTH_USER_MODEL, verbose_name='Petugas Shift Sebelumnya'),
        ),
        migrations.AddField(
            model_name='logbook',
            name='petugas_selanjutnya',
            field=models.ManyToManyField(blank=True, related_name='logs_as_next', to=settings.AUTH_USER_MODEL, verbose_name='Petugas Shift Selanjutnya'),
        ),
    ]
