# Generated by Django 5.2.7 on 2026-01-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0006_remove_logbook_petugas_sebelum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='hv_jam_angkat',
            field=models.TimeField(blank=True, null=True, verbose_name='Jam Pengangkatan HV'),
        ),
        migrations.AddField(
            model_name='logbook',
            name='hv_jam_pasang',
            field=models.TimeField(blank=True, null=True, verbose_name='Jam Pemasangan HV'),
        ),
    ]
