# Generated by Django 5.2.7 on 2026-01-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0007_logbook_hv_jam_angkat_logbook_hv_jam_pasang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='hv_berat_kertas',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Berat Kertas (gr)'),
        ),
    ]
