# Generated by Django 5.2.16 on 2026-10-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0008_alter_logbook_hv_berat_kertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='sirine',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=3, verbose_name='Sirine'),
        ),
    ]
