# Generated by Django 5.2.4 on 2025-09-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SunMoonEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('sun_rise', models.DateTimeField(blank=True, null=True)),
                ('sun_set', models.DateTimeField(blank=True, null=True)),
                ('moon_rise', models.DateTimeField(blank=True, null=True)),
                ('moon_set', models.DateTimeField(blank=True, null=True)),
                ('moon_phase', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'city')},
            },
        ),
    ]
