# Generated by Django 5.2.7 on 2025-12-14 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolaDinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Contoh: P, S, M, PSM, R', max_length=10, unique=True)),
                ('nama', models.CharField(help_text='Contoh: Pagi, Siang, Malam', max_length=50)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('durasi', models.FloatField(help_text='Total jam kerja (decimal). Contoh: 7.5 atau 12.5')),
                ('warna', models.CharField(default='#FFFFFF', help_text='Kode warna Hex, cth: #FF0000', max_length=20)),
                ('is_libur', models.BooleanField(default=False, help_text='Centang jika ini adalah kode untuk Libur/Lepas Dinas/Cuti')),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nip', models.CharField(max_length=30, unique=True)),
                ('pangkat', models.CharField(help_text='Contoh: Penata Muda Tk.I (III/b)', max_length=100)),
                ('jabatan', models.CharField(help_text='Contoh: PMG Pertama', max_length=100)),
                ('is_reguler', models.BooleanField(default=False, help_text='Centang jika pegawai ini pola kerjanya Reguler (Senin-Jumat)')),
                ('urutan', models.IntegerField(default=0, help_text='Untuk mengatur urutan baris di tabel')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='JadwalHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('keterangan_lain', models.CharField(blank=True, choices=[('HADIR', 'Hadir'), ('DL', 'Dinas Luar'), ('CUTI', 'Cuti'), ('SAKIT', 'Sakit'), ('IZIN', 'Izin'), ('TB', 'Tugas Belajar')], help_text='Isi jika status bukan dinas biasa (misal DL/Cuti)', max_length=10, null=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_harian', to='jadwal.pegawai')),
                ('pola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jadwal.poladinas')),
            ],
            options={
                'verbose_name': 'Input Jadwal',
                'verbose_name_plural': 'Input Jadwal',
                'unique_together': {('pegawai', 'tanggal')},
            },
        ),
    ]
