# Generated by Django 5.2.7 on 2025-12-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0002_riwayatjadwal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='tanggal_keluar',
            field=models.DateField(blank=True, help_text='Isi jika pegawai pindah/pensiun. Pegawai otomatis hilang dari jadwal setelah tanggal ini.', null=True),
        ),
    ]
