# Generated by Django 5.2.7 on 2025-12-23 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0004_riwayatjadwal_edited_by_riwayatjadwal_is_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riwayatjadwal',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='riwayatjadwal',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='jadwalharian',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jadwalharian',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
