# Generated by Django 5.2.7 on 2025-12-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0005_remove_riwayatjadwal_edited_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalHVSampler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('tipe', models.CharField(choices=[('PS', 'Pasang Filter SPM (08.00)'), ('AK', 'Angkat Filter SPM (08.00)')], max_length=2)),
                ('catatan_khusus', models.TextField(blank=True, help_text='Contoh: Listrik padam, kebakaran hutan, pembongkaran gedung, dll.', null=True)),
            ],
            options={
                'verbose_name': 'Jadwal HV Sampler',
                'verbose_name_plural': 'Jadwal HV Sampler',
                'ordering': ['tanggal'],
            },
        ),
    ]
