# Generated by Django 5.2.4 on 2026-06-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0006_jadwalhvsampler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lapbul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapbul_obs', models.CharField(max_length=200, verbose_name='Laporan Observasi')),
                ('pic_lapbul_obs', models.CharField(max_length=100, verbose_name='PIC Observasi')),
                ('lapbul_datin', models.CharField(max_length=200, verbose_name='Laporan Data & Informasi')),
                ('pic_lapbul_datin', models.CharField(max_length=100, verbose_name='PIC Data & Informasi')),
                ('bulan', models.IntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Maret'), (4, 'April'), (5, 'Mei'), (6, 'Juni'), (7, 'Juli'), (8, 'Agustus'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Desember')], verbose_name='Bulan')),
                ('data_bulan', models.CharField(help_text='Contoh: Januari 2026', max_length=50, verbose_name='Label Bulan')),
                ('tahun', models.IntegerField(verbose_name='Tahun')),
                ('deadline', models.IntegerField(default=5, help_text='Tanggal deadline setiap bulan (default: 5)', verbose_name='Deadline (tanggal)')),
            ],
            options={
                'verbose_name': 'Lapbul',
                'verbose_name_plural': 'Lapbul',
                'ordering': ['-tahun', '-bulan'],
            },
        ),
    ]
