# Generated by Django 5.2.4 on 2026-06-02 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0007_lapbul_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapbul',
            name='pic_lapbul_datin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pic_datin_lapbul', to='jadwal.pegawai', verbose_name='PIC Data & Informasi'),
        ),
        migrations.AlterField(
            model_name='lapbul',
            name='pic_lapbul_obs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pic_obs_lapbul', to='jadwal.pegawai', verbose_name='PIC Observasi'),
        ),
    ]
