# Generated by Django 5.2.4 on 2026-06-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0008_lapbul_pic_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapbul',
            name='file_lapbul_datin',
            field=models.FileField(blank=True, null=True, upload_to='lapbul/datin/', verbose_name='Dokumen Data & Informasi'),
        ),
        migrations.AddField(
            model_name='lapbul',
            name='file_lapbul_obs',
            field=models.FileField(blank=True, null=True, upload_to='lapbul/obs/', verbose_name='Dokumen Observasi'),
        ),
    ]
