# Generated by Django 5.2.4 on 2026-04-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
