# Generated by Django 5.2.7 on 2025-10-31 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WRSNGStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=datetime.date.today)),
                ('wrs_code', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('display_status', models.IntegerField(choices=[(1, 'OK / Online'), (0, 'Off / Mati')], default=1, help_text='Status monitor display (misal: menyala, mati, error)')),
                ('chrome_status', models.IntegerField(choices=[(1, 'OK / Online'), (0, 'Off / Mati')], default=1, help_text='Status aplikasi (misal: Chrome berjalan, error)')),
                ('remark', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WRSNG Status',
                'verbose_name_plural': 'WRSNG Status',
                'ordering': ['-date', 'wrs_code'],
                'unique_together': {('date', 'wrs_code')},
            },
        ),
    ]
