# Generated by Django 5.2.7 on 2025-11-02 02:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsng', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wrsngstatus',
            options={'ordering': ['-status_datetime', 'wrs_code'], 'verbose_name': 'WRSNG Status Log', 'verbose_name_plural': 'WRSNG Status Logs'},
        ),
        migrations.AlterUniqueTogether(
            name='wrsngstatus',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wrsngstatus',
            name='status_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Waktu pasti status ini dilaporkan'),
        ),
        migrations.RemoveField(
            model_name='wrsngstatus',
            name='date',
        ),
        migrations.RemoveField(
            model_name='wrsngstatus',
            name='last_updated',
        ),
    ]
