# Generated by Django 5.2.7 on 2025-12-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrsng', '0002_alter_wrsngstatus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WRSNGDataAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('percentage', models.FloatField(default=0.0)),
                ('channel', models.CharField(default='REPORT', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WRSNG Data Availability',
                'verbose_name_plural': 'WRSNG Data Availabilities',
                'unique_together': {('station', 'date', 'channel')},
            },
        ),
    ]
